"""add investigation window and notes fields to incidents

Revision ID: 04ca7187bb4c
Revises: 05f549c334a1
Create Date: 2026-07-23 00:23:22.299564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ca7187bb4c'
down_revision: Union[str, None] = '05f549c334a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('window_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('window_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'notes')
    op.drop_column('incidents', 'window_end')
    op.drop_column('incidents', 'window_start')
    # ### end Alembic commands ###
