"""create log_events table

Revision ID: fa1258a15b6a
Revises: 
Create Date: 2026-07-22 06:30:16.797166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1258a15b6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('login_status', sa.String(length=50), nullable=False),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_events_timestamp'), 'log_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_events_username'), 'log_events', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_events_username'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_timestamp'), table_name='log_events')
    op.drop_table('log_events')
    # ### end Alembic commands ###
